[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = ["David Tavan"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Add dependencies here
[dependencies]
