name: Rust CI

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Rust
              uses: actions/checkout@v2
            - name: Install cargo audit
              run: cargo install cargo-audit
            - name: Install cargo-nextest
              run: cargo install cargo-nextest
            - name: Build
              run: cargo build --verbose
            - name: Test
              run: cargo nextest run
            - name: Audit
              run: cargo audit